package psp_t5_55124290y_cliente;

import javax.swing.JOptionPane;

public class interfaz_cliente extends javax.swing.JFrame {

    cliente socketCliente;

    public interfaz_cliente() {
        //Asociar fichero "clientTrustedCerts.jks" al KeyStore
        System.setProperty("javax.net.ssl.trustStore", "clientTrustedCerts.jks");
        //Contraseña
        System.setProperty("javax.net.ssl.trustStorePassword", "claveClienteSecreta");

        initComponents();
        this.setTitle("Almacén de ordenadores - Programa CLIENTE");
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        this.setSize(635, 480);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaConsola = new javax.swing.JTextArea();
        txtMensaje = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnConectarConServidor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbPuerto = new javax.swing.JComboBox<>();
        cbIp = new javax.swing.JComboBox<>();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaConsola.setColumns(20);
        txtAreaConsola.setRows(5);
        jScrollPane1.setViewportView(txtAreaConsola);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 385, 305));
        getContentPane().add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 400, 385, 33));

        btnEnviar.setBackground(new java.awt.Color(255, 255, 255));
        btnEnviar.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(29, 33, 123));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 33));

        btnConectarConServidor.setBackground(new java.awt.Color(51, 153, 0));
        btnConectarConServidor.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnConectarConServidor.setForeground(new java.awt.Color(255, 255, 255));
        btnConectarConServidor.setText("Conectar con servidor");
        btnConectarConServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarConServidorActionPerformed(evt);
            }
        });
        getContentPane().add(btnConectarConServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 180, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(29, 33, 123));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sin título.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 50, 33));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(29, 33, 123));
        jButton2.setText("+1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 305, 50, 33));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(29, 33, 123));
        jButton3.setText("-1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 50, 33));

        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 33, 123));
        jLabel1.setText("Puerto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 33, 123));
        jLabel2.setText("IP:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 33, 123));
        jLabel3.setText("Almacén de ordenadores - CLIENTE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 33, 123));
        jLabel4.setText("Operaciones:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(29, 33, 123));
        jLabel5.setText("Añadir:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(29, 33, 123));
        jLabel6.setText("Eliminar:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 345, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(29, 33, 123));
        jLabel7.setText("Consultar stock:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 275, -1, -1));

        cbPuerto.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        cbPuerto.setForeground(new java.awt.Color(29, 33, 123));
        cbPuerto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8899", "8098", "9090" }));
        getContentPane().add(cbPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        cbIp.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        cbIp.setForeground(new java.awt.Color(29, 33, 123));
        cbIp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "localhost", "127.0.0.1", "192.168.0.1" }));
        getContentPane().add(cbIp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        wallpaper.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        wallpaper.setForeground(new java.awt.Color(29, 33, 123));
        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Wallpaper.png"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarConServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarConServidorActionPerformed
        String server = "";
        int comboIP = cbIp.getSelectedIndex();

        switch (comboIP) {
            case 0:
                server = "localhost";
                break;
            case 1:
                server = "127.0.0.1";
                break;
            case 2:
                server = "192.168.0.1";
                break;
        }

        String puerto = "";
        int comboPuerto = cbPuerto.getSelectedIndex();

        switch (comboPuerto) {
            case 0:
                puerto = "8899";
                break;
            case 1:
                puerto = "8098";
                break;
            case 2:
                puerto = "9090";
                break;
        }

        if (!server.equals("") && !puerto.equals("")) {
            try {
                socketCliente = new cliente(this.txtAreaConsola, server, Integer.parseInt(puerto));
                socketCliente.start();
            } catch (Exception ex) {
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe indicar un una IP y un PUERTO para realizar la conexión.", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConectarConServidorActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        socketCliente.enviar(this.txtMensaje.getText());
        this.txtMensaje.setText("");
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        socketCliente.enviar("+1");
        txtAreaConsola.append("Ha añadido 1 ordenador al stock." + System.lineSeparator());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        socketCliente.enviar("-1");
        txtAreaConsola.append("Ha eliminado 1 ordenador del stock." + System.lineSeparator());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        socketCliente.enviar("CONSULTA DE STOCK");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        System.out.println(
                "***************************************\n"
                + "* PSP - Tarea Individual 5 - Almacén multiusuario *\n"
                + "***************************************\n"
                + "*  Nicolás Esteban Bórquez  *\n"
                + "***************************************\n"
                + "*  55124290Y  *\n"
                + "*************************************** ");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectarConServidor;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cbIp;
    private javax.swing.JComboBox<String> cbPuerto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaConsola;
    private javax.swing.JTextField txtMensaje;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
